[package]
name = "sqlite-wasm-rs"
version = "0.2.4"
edition = "2021"
authors = ["Spxg <unsafe@outlook.es>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/Spxg/sqlite-wasm-rs"
description = "Provide sqlite solution for wasm32-unknown-unknown target."
categories = ["development-tools::ffi", "wasm", "database"]
keywords = ["sqlite", "sqlite-wasm", "wasm", "webassembly", "javascript"]

[dependencies]
fragile = "2.0.0"
once_cell = "1.20.2"
tokio = { version = "1.42.0", features = ["sync"] }

js-sys = "0.3.76"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"

thiserror = { version = "2.0.11", optional = true }
serde = { version = "1.0.216", features = ["derive"], optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
web-sys = { version = "0.3.77", optional = true, features = [
  "Performance",
  "Window",
  "Navigator",
  "StorageManager",
  "FileSystemSyncAccessHandle",
  "FileSystemDirectoryHandle",
  "FileSystemGetDirectoryOptions",
  "FileSystemReadWriteOptions",
  "SharedWorkerGlobalScope",
  "WorkerGlobalScope",
  "WorkerNavigator",
  "TextEncoder",
  "FileSystemGetFileOptions",
  "FileSystemFileHandle",
  "Url",
]}

sqlite-wasm-libc = { path = "../sqlite-wasm-libc", version = "0.1.0", optional = true }

[features]
default = ["shim"]
shim = ["web-sys", "thiserror"]
wrapper = ["serde", "serde-wasm-bindgen"]
custom-libc = ["sqlite-wasm-libc"]
bundled = []

[target.'cfg(target_feature = "atomics")'.dependencies]
parking_lot = "0.12.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.49"

[build-dependencies]
bindgen = "0.71"
xshell = "0.2.7"

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
