[package]
name = "sqlite-wasm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.76"
once_cell = "1.20.2"
parking_lot = "0.12.3"
serde = { version = "1.0.216", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
tokio = { version = "1.42.0", features = ["sync"] }
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
wasm-bindgen-test = "0.3.49"

[dev-dependencies]
futures = { version = "0.3.31", features = ["executor"] }

[features]
loadable_extension = []
