[package]
name = "sqlite-wasm-rs"
version = "0.1.0"
authors = ["Spxg <unsafe@outlook.es>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Spxg/sqlite-wasm-rs"
description = "Wrap sqlite-wasm, and expect to provide a usable C-like API."
categories = ["development-tools::ffi", "wasm", "sqlite"]
keywords = ["sqlite", "javascript", "wasm", "webassembly"]

[dependencies]
fragile = "2.0.0"
js-sys = "0.3.76"
once_cell = "1.20.2"
serde = { version = "1.0.216", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
tokio = { version = "1.42.0", features = ["sync"] }
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"

[dev-dependencies]
wasm-bindgen-test = "0.3.49"

[profile.release]
lto = true
codegen-units = 1
debug = true

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
