name: Precompile
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  precompile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Precompile library
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..
        rustup target add wasm32-unknown-unknown
        SQLITE_WASM_RS_UPDATE_PREBUILD=1 cargo build --target wasm32-unknown-unknown --features bundled
        rm -rf emsdk
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Upload precompiled library and bindings [skip ci]
    - uses: actions/upload-artifact@v4.6.0
      with:
        path: sqlite-wasm-rs/library
