on:
  workflow_dispatch:

jobs:
  precompile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Precompile library
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ../sqlite-wasm-rs
        rustup target add wasm32-unknown-unknown
        SQLITE_WASM_RS_UPDATE_PREBUILD=1 cargo build --target wasm32-unknown-unknown --features bundled
        rm -rf ../emsdk

    - name: Set commit message
      id: commit_message_step
      run: |
        WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        echo 'Upload precompiled library and bindings [skip ci]' >> $GITHUB_OUTPUT
        echo $WORKFLOW_URL >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}

    - uses: actions/upload-artifact@v4.6.0
      with:
        path: sqlite-wasm-rs/library
