name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Test shim
      run: |
        cd sqlite-wasm-rs
        wasm-pack test --chrome --headless
    - name: Test wrapper
      run: |
        cd sqlite-wasm-rs
        wasm-pack test --chrome --headless --no-default-features --features wrapper
    - name: Test custom-libc
      run: |
        cd examples/custom-libc
        RUSTFLAGS="-L $(pwd)" wasm-pack test --chrome --headless
